# Generated by Django 5.2.12 on 2026-03-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='budget_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='budget_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='competition_level',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='competition_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='competition_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='market_demand_level',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='market_demand_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='market_demand_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='market_demand_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='failurerecord',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='failurerecord',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='failurerecord',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
