# Generated by Django 5.2.12 on 2026-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0002_aianalysis_budget_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='improvement_suggestions_list',
            field=models.TextField(blank=True, help_text='JSON list of suggestions'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='success_score',
            field=models.IntegerField(default=0),
        ),
    ]
