# Generated by Django 5.2.12 on 2026-03-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0004_user_ai_notifications_enabled_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EcosystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_startups', models.IntegerField(default=0)),
                ('successful_startups', models.IntegerField(default=0)),
                ('failed_startups', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual growth percentage', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='failures.city')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
                ('is_successful', models.BooleanField(default=True, help_text='True for successful, False for failed')),
                ('count', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='failures.city')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='failures.country')),
            ],
        ),
        migrations.DeleteModel(
            name='StartupData',
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='failures.state'),
        ),
    ]
