# Generated by Django 5.2.12 on 2026-03-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0005_city_country_ecosystemstats_industryperformance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failurerecord',
            name='city_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures_logged', to='failures.city'),
        ),
        migrations.AddField(
            model_name='failurerecord',
            name='state_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures_logged', to='failures.state'),
        ),
    ]
