# Generated by Django 5.2.12 on 2026-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0006_failurerecord_city_model_failurerecord_state_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='interpreted_business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='interpreted_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='interpreted_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
